### ISSUE TITLE
JASMINE var not found by invoking karma directly

### ISSUE THREAD

**Issue by deanrad** [inferinc/bobtail#41]
I'm trying to get Travis CI to build reactive.. 
https://travis-ci.org/chicagogrooves/reactive-coffee

(This will provide the pretty "Build Passing" badge)

Currently the issue is that `grunt` is not found in the Travis environment, so when I try to invoke karma directly to fix that, errors.. shown below...

Yang - Do you know how grunt-jasmine resolves the JASMINE/JASMINE_ADAPTER variables ? Have you considered any different build platforms ? 

`./node_modules/grunt-karma/node_modules/.bin/karma start --single-run --browsers PhantomJS
ERROR [config]: Invalid config file!
  ReferenceError: JASMINE is not defined
    at Object.<anonymous> (/Users/dean/src/reactive-coffee/karma.conf.js:8:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.parseConfig (/Users/dean/src/reactive-coffee/node_modules/karma/lib/config.js:250:22)
    at Object.exports.start (/Users/dean/src/reactive-coffee/node_modules/karma/lib/server.js:273:20)`

**Comment by deanrad** [comment]
This doesn't matter now that I figured out how to get grunt builds to work on Travis CI.
